Database test
bookshift/bookshift pull request #24
Opened 2024-02-13 22:05 UTC by AnthonyClarke25

2024-02-13 22:09 UTC, DMCFA requested changes

2024-02-13 22:09 UTC, DMCFA commented on src/db/index.ts
> +  console.log(allUsers);
I would say to remove this if it's working

2024-02-13 22:09 UTC, DMCFA commented on src/app/page.tsx
This is wrong and overriding my work from yesterday

2024-02-14 20:56 UTC, AnthonyClarke25 commented on src/app/page.tsx
i hit to wrong side on the merge reverted back

2024-02-14 21:29 UTC, DMCFA approved these changes

2024-02-14 21:30 UTC, merged