create messaages
bookshift/bookshift pull request #27
Opened 2024-02-24 17:07 UTC by AnthonyClarke25

ok so this pr isn't a simple one and small one sorry in advance.  while trying to figure out some things i ended up doing most of the functionality of a base chat. 

The basic gist is in the chat window you click on a user, using a click function being passed down from the chat page through the chat user list to the chat user component, This returns that users id which is then passed to the chat window component. 

After this is done when the submit function is called on the chat window uses the logged in users id ( passed from the page), and the updated receiving user id ( which is set from the other component using the state hook) and the typed in message to create a message which can been seen in the console https://app.planetscale.com/bookshift/bookshift/initial-setup/console and running 'select * from messages;'

2024-02-25 13:01 UTC, DMCFA reviewed
will try to run it later to give it a go but left a few comments

2024-02-25 13:01 UTC, DMCFA commented on src/app/(dashboard)/chat/page.tsx
> +  const { isSignedIn, user } = useUser();
I remember this being used on the root base page, would it be a better idea to run it there once on load and host that info on a context hook and then use it from there instead of calling it multiple times throughout the application?

2024-02-25 13:01 UTC, DMCFA commented on src/app/(dashboard)/chat/page.tsx
> +  if (isSignedIn) {
this is the same check we have on the root page as well to give more context to my comment above

2024-02-25 13:01 UTC, DMCFA commented on src/components/ChatUserInputForm.tsx
> +  const handleInputChange = (e: any) => {
why have you decided to use any here?

2024-02-25 18:23 UTC, AnthonyClarke25 commented on src/app/(dashboard)/chat/page.tsx
> +  const { isSignedIn, user } = useUser();
i tried that but i couldn't get that to work, if you can then that would be much better. I think this might be me missing something

2024-02-25 18:23 UTC, AnthonyClarke25 commented on src/app/(dashboard)/chat/page.tsx
> +  if (isSignedIn) {
once again happy for this to be changed but ii wasn't able to get this to work

2024-02-25 18:24 UTC, AnthonyClarke25 commented on src/components/ChatUserInputForm.tsx
> +  const handleInputChange = (e: any) => {
i wasn't sure what the correct type should be and i couldn't find it while googling

2024-02-25 19:59 UTC, DMCFA requested changes

2024-02-25 19:59 UTC, DMCFA commented on src/components/ChatUserInputForm.tsx
> +  const handleInputChange = (e: any) => {
I would try
`const handleInputChange = (e: ChangeEvent<HTMLInputElement>) => {
        setInputValue(e.target.value);
  };`
  
 You will need to import ChangeEvent from react.

2024-02-25 19:59 UTC, DMCFA commented on src/app/(dashboard)/chat/page.tsx
> +  const { isSignedIn, user } = useUser();
we can have a bette look later on

2024-02-25 22:53 UTC, AnthonyClarke25 commented on src/components/ChatUserInputForm.tsx
> +  const handleInputChange = (e: any) => {
updated seems to work ok

2024-02-26 07:17 UTC, DMCFA approved these changes

2024-02-26 09:02 UTC, merged